/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Concepto;
import Models.Diccionario;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    // creamos nuestro dicionario q usaremos
    private Diccionario dicionario;
    private boolean cargandoDefinicion = false;

    public PantallaPrincipal() {
        initComponents();
        jPopupMenu1.setFocusable(false);
        dicionario = new Diccionario();
        this.setLocationRelativeTo(null); // centrar ventana para q no se mueva cada q sugiera completar
        iniciarAutoCompletado();
        // ═══════════════════════════════════════════════
        // DATOS DE PRUEBA PARA EL DICCIONARIO
        // ═══════════════════════════════════════════════
        /*
         * // Letra A (Ideal para probar autocompletado con "A" y "AR")
         * dicionario.agregarConcepto("ARRAY",
         * "Es un conjunto de datos primitivos o básicos (como int, boolean, etc.) almacenados en posiciones contiguas de memoria."
         * );
         * dicionario.agregarConcepto("ARBOL BINARIO",
         * "Estructura de datos jerárquica donde cada nodo tiene como máximo dos hijos (izquierdo y derecho)."
         * );
         * dicionario.agregarConcepto("ALGORITMO",
         * "Conjunto de pasos lógicos, definidos y finitos que resuelven un problema o realizan una tarea."
         * );
         * dicionario.agregarConcepto("ARCHIVO",
         * "Conjunto de información digital almacenada bajo un nombre específico en un medio de almacenamiento."
         * );
         * 
         * // Letra B
         * dicionario.agregarConcepto("BUCLE",
         * "Secuencia de instrucciones de código que se repite hasta que se cumple una condición específica (ej. for, while)."
         * );
         * dicionario.agregarConcepto("BOOLEAN",
         * "Tipo de dato primitivo que solo puede tener dos valores: verdadero (true) o falso (false)."
         * );
         * 
         * // Letra C (Ideal para probar autocompletado con "CO")
         * dicionario.agregarConcepto("CLASE",
         * "Plantilla para crear objetos en la Programación Orientada a Objetos. Define atributos y métodos."
         * );
         * dicionario.agregarConcepto("COMPILADOR",
         * "Programa que traduce el código fuente escrito por un humano a lenguaje de máquina que la computadora entiende."
         * );
         * dicionario.agregarConcepto("CONSTRUCTOR",
         * "Método especial de una clase que se ejecuta automáticamente al crear un nuevo objeto (instancia)."
         * );
         * 
         * // Otras letras variadas
         * dicionario.agregarConcepto("DEBUG",
         * "Proceso de identificar, analizar y corregir errores (bugs) en el código de un programa."
         * );
         * dicionario.agregarConcepto("ENCAPSULAMIENTO",
         * "Mecanismo que oculta los datos internos de un objeto, protegiéndolos mediante modificadores como 'private'."
         * );
         * dicionario.agregarConcepto("HERENCIA",
         * "Pilar de la POO que permite a una clase (hija) heredar los atributos y métodos de otra clase (padre)."
         * );
         * dicionario.agregarConcepto("INTERFAZ",
         * "Contrato en Java que define qué métodos debe tener una clase, pero sin programar cómo funcionan por dentro."
         * );
         * dicionario.agregarConcepto("METODO",
         * "Bloque de código dentro de una clase que contiene una serie de instrucciones para realizar una acción específica."
         * );
         * dicionario.agregarConcepto("POLIMORFISMO",
         * "Capacidad de un objeto o método de tomar muchas formas o comportarse de distintas maneras según el contexto."
         * );
         * dicionario.agregarConcepto("VARIABLE",
         * "Espacio reservado en la memoria RAM de la computadora para almacenar un dato que puede cambiar durante la ejecución."
         * );
         */

        // Cargar los datos desde el archivo de texto
        dicionario.cargarDesdeArchivo("C:\\Users\\User\\Documents\\NetBeansProjects\\AutocompletarPalabras\\test\\conceptos.txt");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();

        jPopupMenu1.setBackground(new java.awt.Color(204, 204, 204));
        jPopupMenu1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(15, 23, 42));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DICCIONARIO");

        jPanel2.setBackground(new java.awt.Color(30, 41, 59));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 4, true));

        jTextPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Escriba una palabra");

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        jButton1.setText("Agregar Palabra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                .addGap(69, 69, 69)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addGap(984, 984, 984))
        );

        jButton1.getAccessibleContext().setAccessibleDescription("");

        jPanel4.setBackground(new java.awt.Color(30, 41, 59));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 65, 85), 4, true));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripcion de la palabra:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NONE");

        jTextPane3.setBackground(new java.awt.Color(204, 204, 204));
        jTextPane3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jScrollPane3.setViewportView(jTextPane3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        jButton2.setText("CargarDeOtroArchivo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser selectorArchivos = new JFileChooser();
        selectorArchivos.setDialogTitle("Seleccione el archivo del diccionario");

        // Filtrar para que solo se puedan seleccionar archivos .txt
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de Texto (.txt)", "txt");
        selectorArchivos.setFileFilter(filtro);

        int resultado = selectorArchivos.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = selectorArchivos.getSelectedFile();

            // Vaciar el diccionario actual antes de cargar uno nuevo si lo deseas
            dicionario.vaciar();

            // Cargar los nuevos datos
            dicionario.cargarDesdeArchivo(archivoSeleccionado.getAbsolutePath());

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Archivo cargado correctamente.", "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void iniciarAutoCompletado() {
        jTextPane1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                if (!cargandoDefinicion) {
                    runActualizar();
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if (!cargandoDefinicion) {
                    runActualizar();
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                if (!cargandoDefinicion) {
                    runActualizar();
                }
            }

            private void runActualizar() {
                SwingUtilities.invokeLater(() -> actualizarSugerencias());
            }
        });
    }

    private void actualizarSugerencias() { //aqui cargamos las sugerencias 
        if (cargandoDefinicion) {
            return;
        }
        String texto = jTextPane1.getText().trim();
        if (texto.isEmpty()) {// si no hay nada escrito no haga nada
            jPopupMenu1.setVisible(false);
            return;
        }
        List<Concepto> sugerencias = dicionario.autoCompletar(texto);
        jPopupMenu1.removeAll();
        if (sugerencias.isEmpty()) {
            jPopupMenu1.setVisible(false);
            return;
        }
        for (Concepto c : sugerencias) {
            JMenuItem item = new JMenuItem(c.obtenerPalabra());
            item.setFocusable(false);
            item.addActionListener(e -> mostrarDefinicion(c));
            jPopupMenu1.add(item);
        }
        jPopupMenu1.show(jTextPane1, 0, jTextPane1.getHeight());
    }

    private void mostrarDefinicion(Concepto concepto) {
        cargandoDefinicion = true;
        try {
            jPopupMenu1.setVisible(false);
            jLabel5.setText(concepto.obtenerPalabra().toUpperCase());
            jTextPane3.setText(concepto.obtenerDefinicion());
            jTextPane1.setText(concepto.obtenerPalabra());
        } finally {
            cargandoDefinicion = false;
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String palabra = JOptionPane.showInputDialog(this,
                "Ingrese la palabra:", "Agregar Concepto", JOptionPane.PLAIN_MESSAGE);
        if (palabra == null || palabra.trim().isEmpty()) {
            return;
        }
        String definicion = JOptionPane.showInputDialog(this,
                "Ingrese la definición:", "Definición de " + palabra, JOptionPane.PLAIN_MESSAGE);
        if (definicion == null) {
            definicion = "";
        }
        try {
            dicionario.agregarConcepto(palabra, definicion);
            JOptionPane.showMessageDialog(this,
                    "\"" + palabra + "\" agregado correctamente.",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this,
                    "\"" + palabra + "\" ya existe en el diccionario.",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
